name: Reusable Workflow to Deploy .NET App

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      app-name:
        required: true
        type: string
      deployment-slot:
        required: true
        type: string
    
jobs:

  deploy:
    runs-on: windows-latest
    steps:      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.package-name }}

      - run: echo "Workflow stored in shared repo"
        
      - name: Print name of App Service to deploy to
        run: echo "App will be deployed to ${{ inputs.app-name }}"
      
      - name: List files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
