name: Reusable Workflow to Deploy .NET App

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      app-name:
        required: true
        type: string
      deployment-slot:
        required: true
        type: string
    secrets:
      someSecret:
        required: true
    
jobs:

  deploy:
    runs-on: windows-latest
      
    steps:      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.package-name }}

      - name: Print Location
        run: echo "Workflow stored in shared repo test3"

      - name: Test secret value
        run: echo "Value of passed secret matches known value: $SECRET_MATCH"
        env:
          SECRET_MATCH: ${{ secrets.someSecret == 'Some Value' }}
      
      - name: Print name of App Service to deploy to
        run: echo "App will be deployed to ${{ inputs.app-name }}"
      
      - name: List files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
